version: "2"

services:
  app_base:
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "dockerhost:${DOCKER_HOST_IP}"
      - "qc.local:${HOST_BRIDGE_IP}"
      - "api-internal.qc.local:${HOST_BRIDGE_IP}"
      - "billing.local:${HOST_BRIDGE_IP}"
      - "ads-data-management.local:${HOST_BRIDGE_IP}"
      - "ads-data-server.local:${HOST_BRIDGE_IP}"
      - "moderation-tool.local:${HOST_BRIDGE_IP}"
      - "moderation-api.local:${HOST_BRIDGE_IP}"
      - "skin-tool.local:${HOST_BRIDGE_IP}"
      - "old-skin-tool.local:${HOST_BRIDGE_IP}"
      - "crawler.test:${HOST_BRIDGE_IP}"
      - "old-moderation-api.local:${HOST_BRIDGE_IP}"

      - "publisher.local:${HOST_BRIDGE_IP}"
      - "operation.local:${HOST_BRIDGE_IP}"
      - "ad-tag.local:${HOST_BRIDGE_IP}"
      - "sonar.local:${HOST_BRIDGE_IP}"
    environment:
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - COMPOSER_MEMORY_LIMIT=-1
    build:
      dockerfile: Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
        - PHP_OPCACHE_VALIDATE_TIMESTAMPS=${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
        - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/site_categories.json:/var/lib/labs/site_categories.json
      - ./php-fpm/skin-tool/rsync_password.txt:/etc/coccoc/browser_skin_admin_tool/rsync_password.txt
      - ./php-fpm/skin-tool/clickhouse-user-browser_skin_admin-credentials.json:/etc/coccoc-clickhouse-labs/conf/clickhouse-user-browser_skin_admin-credentials.json
      - /tmp/skin-demo:/var/itim/skin-demo.coccoc.com/public/
    cap_add:
      - SYS_ADMIN
    