version: '2'
services:

  php-fpm-7.2:
    build:
      context: ./php-fpm-7.2
      dockerfile: Dockerfile
      args:
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    image: backend-php-fpm-7.2
    container_name: php-fpm-7.2
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm-7.2/site_categories.json:/var/lib/labs/site_categories.json
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - backend
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "moderation-tool.local:${HOST_BRIDGE_IP}"
      - "moderation-api.local:${HOST_BRIDGE_IP}"

  php-fpm-8.0:
    build:
      context: ./php-fpm-8.0
      dockerfile: Dockerfile
      args:
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    image: backend-php-fpm-8.0
    container_name: php-fpm-8.0
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - backend
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "moderation-tool.local:${HOST_BRIDGE_IP}"
      - "moderation-api.local:${HOST_BRIDGE_IP}"

  php-worker-8.0:
    container_name: php-worker-8.0
    build:
      context: ./php-worker-8.0
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-worker/supervisord.d:/etc/supervisord.d
    networks:
      - backend
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "moderation-tool.local:${HOST_BRIDGE_IP}"
      - "moderation-api.local:${HOST_BRIDGE_IP}"

  #Nginx Service
  nginx:
    build:
      context: ./nginx
    container_name: backend-nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    networks:
      - backend
    depends_on:
      - php-fpm-8.0
      - php-fpm-7.2
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "moderation-tool.local:${HOST_BRIDGE_IP}"
      - "moderation-api.local:${HOST_BRIDGE_IP}"

  #MySQL Service
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: backend-mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  #REDIS Service
  redis:
    build: ./redis
    container_name: backend-redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  redis-cluster:
    image: 'phuongdm1987/docker-redis-cluster:1.0.0'
    container_name: backend-redis-cluster
    volumes:
      - 'redis-cluster:/data'
    ports:
      - '7000-7005:7000-7005'
    environment:
      DEFAULT_PASSWORD: 'secret'
    networks:
      - backend

  redis-master:
    image: redis:latest
    container_name: backend-redis-master
    ports:
      - "${REDIS_MASTER_PORT}:6379"
    volumes:
      - redis-master:/var/lib/redis
    networks:
      - backend

  redis-slave:
    image: redis:latest
    container_name: backend-redis-slave
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master:redis-master
    networks:
      - backend

  redis-sentinel:
    build: ./redis-sentinel
    container_name: backend-redis-sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - redis-master:redis-master
      - redis-slave
    ports:
      - "${REDIS_SENTINEL_PORT}:26379"
    networks:
      - backend

  ### RabbitMQ #############################################

  rabbitMQ:
    image: rabbitmq:3-management
    hostname: "${RABBITMQ_HOST_NAME}"
    container_name: backend-rabbitMQ
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    volumes:
      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq
      - ${PWD}/rabbitMQ/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - backend

  ### MongoDB ##############################################
  mongodb:
    image: mongo:latest
    container_name: backend-mongodb
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongodb:/data/db
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - backend

  ### ElasticSearch ########################################
  elasticsearch:
    build: ./elasticsearch
    container_name: backend-elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=laravel-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    networks:
      - backend

  clickhouse:
    image: yandex/clickhouse-server:19.15.3.6
    container_name: backend-clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8124"
      - "${CLICKHOUSE_CLIENT_PORT}:9002"
    volumes:
      - clickhouse:/var/lib/clickhouse
      - ${PWD}/clickhouse/dictionary/external_placement_dictionary.xml:/etc/clickhouse-server/external_placement_dictionary.xml
      - ${PWD}/clickhouse/config.xml:/etc/clickhouse-server/config.xml
    networks:
      - backend

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: backend-mailhog
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_HTTP_PORT}:8025"
    networks:
      - backend

#Docker Networks
networks:
  backend:
    driver: ${NETWORKS_DRIVER}
#Volumes
volumes:
  redis:
    driver: ${VOLUMES_DRIVER}
  redis-master:
    driver: ${VOLUMES_DRIVER}
  redis-cluster:
    driver: ${VOLUMES_DRIVER}
  mongodb:
    driver: ${VOLUMES_DRIVER}
  clickhouse:
    driver: ${VOLUMES_DRIVER}
  elasticsearch:
    driver: ${VOLUMES_DRIVER}
